web/router.ex
defmodule DevLocker.Router do
  use DevLocker.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", DevLocker do
    pipe_through :browser # Use the default browser stack

    get "/", LockerController, :index
    get "/sign_in", SessionController, :new
    delete "/sign_out", SessionController, :delete
    resources "/sessions", SessionController
    resources "/users", UserController
    resources "/lockers", LockerController
  end

  # Other scopes may use custom stacks.
  # scope "/api", DevLocker do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule DevLocker.LayoutView do
  use DevLocker.Web, :view

  def current_user(conn) do
    DevLocker.Repo.get(DevLocker.User, current_user_id(conn))
  end

  def current_user_id(conn) do
    case user_id = conn.private.plug_session["user_id"] do
      is_integer -> user_id
      _ -> nil
    end
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>DevLocker</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container" role="main">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <%= if current_user_id(@conn) do %>
        <p> Signed In As <%= DevLocker.User.full_name(current_user(@conn))  %>
        <%= link "Sign out", to: session_path(@conn, :delete), method: :delete %></p>
      <% end %>

      <%= @inner %>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>

    <script>require("web/static/js/app")</script>

  </body>
</html>